test_average (__main__.TestExercice) ... ok
test_square (__main__.TestExercice) ... ok
test_square_root (__main__.TestExercice) ... ok
test_to_celsius (__main__.TestExercice) ... ok
test_to_degrees (__main__.TestExercice) ... FAIL
test_to_farenheit (__main__.TestExercice) ... ok
test_to_radians (__main__.TestExercice) ... ok

======================================================================
FAIL: test_to_degrees (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 86, in test_to_degrees
    'Mauvais calcul de radians -> degres'
AssertionError: Lists differ: [(114.59155902616465, 1.909859317102744, 0.[203 chars]518)] != [(79.0980174562859, 5.881047377154118, 29.6[197 chars]998)]

First differing element 0:
(114.59155902616465, 1.909859317102744, 0.03183098861837907)
(79.0980174562859, 5.881047377154118, 29.612494192724625)

- [(114.59155902616465, 1.909859317102744, 0.03183098861837907),
-  (-229.1831180523293, -3.819718634205488, -0.06366197723675814),
-  (286.4788975654116, 4.7746482927568605, 0.07957747154594767),
-  (234.33973820850667, 3.9056623034751112, 0.06509437172458518)]
+ [(79.0980174562859, 5.881047377154118, 29.612494192724625),
+  (-278.1960349125718, 48.23790524569176, 0.7750116145507491),
+  (257.74504364071475, -15.297381557114704, 44.031235481811564),
+  (213.95544569810457, -2.673258113725865, 23.057550624127998)] : Mauvais calcul de radians -> degres

----------------------------------------------------------------------
Ran 7 tests in 0.005s

FAILED (failures=1)
